# Generated by Django 3.1.2 on 2020-11-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20201111_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
