# Generated by Django 3.1.2 on 2020-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20201113_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
